import { DogIcon, HeartIcon, UsersIcon, DropletsIcon, AlertTriangleIcon, BrainIcon } from "lucide-react";

export const trainingModules = [
  {
    id: "starthere",
    title: "Comece Aqui 🎯",
    description: "Fundamentos essenciais para começar a treinar seu cão",
    duration: "1 hora",
    route: "/content/training/starthere",
    icon: DogIcon,
    lessons: [
      {
        id: "starthere1",
        title: "Introdução ao Adestramento",
        description: "Entenda os conceitos básicos do adestramento positivo",
        duration: "10 min",
        component: "StartHere1",
      },
      {
        id: "starthere2",
        title: "Comunicação com seu Cão",
        description: "Aprenda a se comunicar efetivamente com seu cão",
        duration: "15 min",
        component: "StartHere2",
      },
      {
        id: "starthere3",
        title: "Recompensas e Reforço Positivo",
        description: "Como usar recompensas para motivar seu cão",
        duration: "15 min",
        component: "StartHere3",
      },
      {
        id: "starthere4",
        title: "Timing e Consistência",
        description: "A importância do timing e da consistência no treinamento",
        duration: "15 min",
        component: "StartHere4",
      },
      {
        id: "starthere5",
        title: "Ambiente de Treinamento",
        description: "Como criar o ambiente ideal para o treinamento",
        duration: "15 min",
        component: "StartHere5",
      },
    ],
  },
  {
    id: "behavior",
    title: "Comportamento Essencial 🐕",
    description: "Comandos básicos e comportamentos essenciais para o dia a dia",
    duration: "1 hora e 15 minutos",
    route: "/content/training/behavior",
    icon: HeartIcon,
    lessons: [
      {
        id: "behavior1",
        title: "Comandos Básicos: Senta e Deita",
        description: "Aprenda a ensinar os comandos básicos de obediência",
        duration: "15 min",
        component: "Behavior1",
      },
      {
        id: "behavior2",
        title: "Comandos Básicos: Fica e Vem",
        description: "Controle e chamada do seu cão em diferentes situações",
        duration: "15 min",
        component: "Behavior2",
      },
      {
        id: "behavior3",
        title: "Comandos Básicos: Junto e Solta",
        description: "Passeio com guia e controle de objetos",
        duration: "15 min",
        component: "Behavior3",
      },
      {
        id: "behavior4",
        title: "Comandos Básicos: Não e Quieto",
        description: "Controle de comportamentos indesejados",
        duration: "15 min",
        component: "Behavior4",
      },
      {
        id: "behavior5",
        title: "Comandos Básicos: Busca e Entrega",
        description: "Jogos e brincadeiras para fortalecer o vínculo",
        duration: "15 min",
        component: "Behavior5",
      },
    ],
  },
  {
    id: "socialization",
    title: "Socialização e Controle 🎭",
    description: "Desenvolva a sociabilidade e o controle de impulsos do seu cão",
    duration: "1 hora e 25 minutos",
    route: "/content/training/socialization",
    icon: UsersIcon,
    lessons: [
      {
        id: "socialization1",
        title: "Como socializar o cão com pessoas e outros pets",
        description: "Técnicas para socializar seu cão com diferentes tipos de pessoas e animais",
        duration: "15 min",
        component: "Socialization1",
      },
      {
        id: "socialization2",
        title: "Passeio sem puxar a guia",
        description: "Aprenda a ensinar seu cão a caminhar sem puxar a guia",
        duration: "15 min",
        component: "Socialization2",
      },
      {
        id: "socialization3",
        title: "Latidos excessivos: Como reduzir e controlar",
        description: "Métodos para controlar e reduzir latidos excessivos",
        duration: "15 min",
        component: "Socialization3",
      },
      {
        id: "socialization4",
        title: "Ensinar a não pular em visitas",
        description: "Técnicas para evitar que seu cão pule em visitas",
        duration: "15 min",
        component: "Socialization4",
      },
      {
        id: "socialization5",
        title: "Controle na hora da refeição",
        description: "Evitar ansiedade e possessividade durante as refeições",
        duration: "15 min",
        component: "Socialization5",
      },
      {
        id: "socialization6",
        title: "Ensinar a aceitar manuseio",
        description: "Preparar seu cão para visitas ao veterinário, banho e tosa",
        duration: "15 min",
        component: "Socialization6",
      },
    ],
  },
  {
    id: "hygiene",
    title: "Higiene e Rotina 🧼",
    description: "Estabeleça uma rotina saudável de higiene para seu cão",
    duration: "1 hora",
    route: "/content/training/hygiene",
    icon: DropletsIcon,
    lessons: [
      {
        id: "hygiene1",
        title: "Ensinando o Local Correto",
        description: "Como ensinar seu cão onde fazer suas necessidades",
        duration: "15 min",
        component: "Hygiene1",
      },
      {
        id: "hygiene2",
        title: "Rotina de Alimentação",
        description: "Estabelecendo horários e hábitos alimentares saudáveis",
        duration: "15 min",
        component: "Hygiene2",
      },
      {
        id: "hygiene3",
        title: "Caixa de Transporte",
        description: "Acostumando seu cão com a caixa de transporte",
        duration: "15 min",
        component: "Hygiene3",
      },
      {
        id: "hygiene4",
        title: "Preservando os Móveis",
        description: "Evitando que seu cão destrua móveis e objetos",
        duration: "15 min",
        component: "Hygiene4",
      },
    ],
  },
  {
    id: "badhabits",
    title: "Evitando Maus Hábitos ⚠️",
    description: "Prevenção e correção de comportamentos indesejados",
    duration: "1 hora",
    route: "/content/training/badhabits",
    icon: AlertTriangleIcon,
    lessons: [
      {
        id: "badhabits1",
        title: "Mordidas e Mastigação",
        description: "Como controlar mordidas e mastigação excessiva",
        duration: "15 min",
        component: "BadHabits1",
      },
      {
        id: "badhabits2",
        title: "Roubo de Comida",
        description: "Evitar que o cão roube comida da mesa",
        duration: "15 min",
        component: "BadHabits2",
      },
      {
        id: "badhabits3",
        title: "Pular nas Pessoas",
        description: "Como evitar que o cão pule nas pessoas",
        duration: "15 min",
        component: "BadHabits3",
      },
      {
        id: "badhabits4",
        title: "Destruição de Móveis",
        description: "Evitar que o cão destrua móveis e objetos",
        duration: "15 min",
        component: "BadHabits4",
      }
    ],
  },
  {
    id: "mental",
    title: "Exercícios Mentais e Diversão",
    description: "Atividades para estimular a mente do seu cão",
    icon: "🧩",
    lessons: [
      {
        id: "mental1",
        title: "Brinquedos Interativos",
        description: "Enriquecimento ambiental com brinquedos interativos",
        duration: "15 min",
        component: "Mental1",
      },
      {
        id: "mental2",
        title: "Jogos para Gastar Energia",
        description: "Atividades divertidas para dentro de casa",
        duration: "15 min",
        component: "Mental2",
      },
      {
        id: "mental3",
        title: "Truques Simples",
        description: "Truques divertidos para ensinar ao seu cão",
        duration: "15 min",
        component: "Mental3",
      },
      {
        id: "mental4",
        title: "Esportes Caninos",
        description: "Introdução aos principais esportes caninos",
        duration: "15 min",
        component: "Mental4",
      },
    ],
  },
]; 